#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr

bspc monitor HDMI-1 -d 1 2 3 4 5

bspc config border_width         2
bspc config normal_border_color  "#000000"
bspc config active_border_color  "#000000"
bspc config focused_border_color "#ff0000"
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
