vim.cmd('autocmd BufWritePost ~/.local/src/dmenu/config.h silent !cd ~/.local/src/dmenu/; doas make -j"$(nproc)" clean install')
vim.cmd('autocmd BufWritePost ~/.local/src/dwm/config.h !cd ~/.local/src/dwm/; doas make -j"$(nproc)" clean install && kill -HUP $(pidof dwm)')
vim.cmd('autocmd BufWritePost ~/.local/src/qmk_firmware/keyboards/keychron/v1/ansi_encoder/keymaps/custom/keymap.c !cd ~/.local/src/qmk_firmware && qmk --no-color compile -kb keychron/v1/ansi_encoder -km custom && qmk --no-color flash -kb keychron/v1/ansi_encoder -km custom')
vim.cmd('autocmd BufWritePost ~/.local/src/st/config.h !cd ~/.local/src/st/; doas make -j"$(nproc)" clean install')
vim.cmd('autocmd BufWritePost ~/.config/sway/config silent !swaymsg -q reload')
vim.cmd('autocmd BufWritePost ~/.config/river/init silent !sh ~/.config/river/init ')
vim.cmd('autocmd BufWritePost ~/.config/spectrwm/spectrwm.conf silent !xdotool key super+F4')
vim.cmd('autocmd BufWritePost ~/.config/ratpoison/ratpoisonrc silent !killall ratpoison')
vim.cmd('autocmd BufWritePost ~/.config/bspwm/bspwmrc silent !bspc wm -r')
vim.cmd('autocmd BufWritePost ~/.config/river/init !sh ~/.config/river/init')
vim.cmd('autocmd BufWritePost ~/.config/sxhkd/sxhkdrc silent !pkill -USR1 -x sxhkd')
